### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by giswqs** [pyvista/pyvista-xarray#23]
Nice package! I would like to integrate it with leafmap. Have you considered getting the package on conda-forge? I would be happy to get it on conda-forge and then transfer ownership to you. Let me know.

**Comment by banesullivan** [comment]
I'm going through a dev cycle on this right now and the API will change quite a bit. After the next release, I will add a `conda-forge` recipe for this!

**Comment by giswqs** [comment]
Great! Looking forward to it. Thank you for another great package for geospatial
