### ISSUE TITLE
Nodata issue

### ISSUE THREAD

**Issue by giswqs** [pyvista/pyvista-xarray#34]
I am trying to display an [elevation dataset](https://drive.google.com/file/d/1OY3kP4o5_OoBn66nnSg6pjJmaA25A03_/view?usp=sharing), but it seems pyvista-xarray somehow uses the nodata value as the minimum value to render the data, making it look like a long vertical column. Is it possible to specify a minimum value to prevent pyxarray from using the nodata value for rendering?

```python
import rioxarray

da = rioxarray.open_rasterio("madison.tif")
da = da.rio.reproject("EPSG:3857")

# Grab the mesh object for use with PyVista
mesh = da[dict(band=0)].pyvista.mesh(x="x", y="y")

# plot in 3D
mesh.warp_by_scalar().plot()
```

![image](https://user-images.githubusercontent.com/5016453/180299215-35d9dacf-9d34-416b-984b-a60fcd8375a0.png)

Rendering the original lidar point cloud
```python
import leafmap
leafmap.view_lidar('madison.las', cmap='terrain')
```
![image](https://user-images.githubusercontent.com/5016453/180299564-ab59288d-3469-4190-bb88-517f44ab990b.png)

**Comment by giswqs** [comment]
The minimum and maximum values of the GeoTIFF are recognized by QGIS correctly. Not sure why pyxarray does not recognize them. 

![image](https://user-images.githubusercontent.com/5016453/180300780-f009dbe6-1678-4a52-950d-2b7b13b8ede9.png)

**Comment by banesullivan** [comment]
> The minimum and maximum values of the GeoTIFF are recognized by QGIS correctly. Not sure why pyxarray does not recognize them.

The `nodata` value is in the metadata of the geotiff itself. If you have `rioxarray` installed, we could use that accessor to get the `nodata` value programmatically (as I do above)

This is actually a bit of a nuanced issue, and my *exhausted* brain doesn't have a great solution for you at the moment... the solution I provide in #35 has what could be serious side effects by modifying the data inplace or copying the values (converting int to float and thus blowing up memory usage for large datasets)

**Comment by giswqs** [comment]
Thanks for looking into it. The issue seems a bit more complicated than I expected. `da.rio.nodata` can indeed get the nodata value. `-32768.0` seems quite commonly used for nodata. Can we modify the GeoTIFF nodata value to zero or a value slighly smaller than the minimum value? This can potentially create new GeoTIFF that works with pvxarray. What I meant is to prepare an input file that will works with pvxarray rather than asking pvxarray to deal with such nodata issue.

![image](https://user-images.githubusercontent.com/5016453/180357398-eea377f6-f0e5-4b05-b580-cd9a8c142d24.png)
