### ISSUE TITLE
import pvxarray fails

### ISSUE THREAD

**Issue by almaniac** [pyvista/pyvista-xarray#43]
After a pip install, I tried the very simple example in the readme.  When trying to import pvxarray I get the following error:

DLL load failed while importing vtkIONetCDF: The specified procedure could not be found.

Here's the code up to the point where it fails:
import pyvista as pv
import numpy as np
import xarray as xr
import pvxarray

**Comment by banesullivan** [comment]
Would you please include the full trace back and either a `pip list` or `conda list` of your environment?

**Comment by ThomasMGeo** [comment]
Had a similar issue, here is the traceback and my pip list

`Package                       Version
----------------------------- -----------
aiohttp                       3.8.3
aiosignal                     1.2.0
anyio                         3.6.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.8
async-timeout                 4.0.2
attrs                         22.1.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.1
bleach                        5.0.1
brotlipy                      0.7.0
Cartopy                       0.21.0
certifi                       2022.9.24
cffi                          1.15.1
cftime                        1.6.2
charset-normalizer            2.1.1
contourpy                     1.0.5
cryptography                  38.0.2
cycler                        0.11.0
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
entrypoints                   0.4
executing                     1.1.1
fastjsonschema                2.16.2
flit_core                     3.7.1
fonttools                     4.38.0
frozenlist                    1.3.1
idna                          3.4
imageio                       2.22.0
importlib-metadata            5.0.0
importlib-resources           5.10.0
ipykernel                     6.16.2
ipython                       8.5.0
ipython-genutils              0.2.0
jedi                          0.18.1
Jinja2                        3.1.2
json5                         0.9.5
jsonschema                    4.16.0
jupyter_client                7.4.4
jupyter_core                  4.11.1
jupyter-server                1.21.0
jupyterlab                    3.5.0
jupyterlab-pygments           0.2.2
jupyterlab_server             2.16.1
kiwisolver                    1.4.4
loguru                        0.6.0
MarkupSafe                    2.1.1
matplotlib                    3.6.1
matplotlib-inline             0.1.6
MetPy                         1.2.0
mistune                       2.0.4
multidict                     6.0.2
munkres                       1.1.4
nbclassic                     0.4.7
nbclient                      0.7.0
nbconvert                     7.2.2
nbformat                      5.7.0
nest-asyncio                  1.5.6
netCDF4                       1.6.1
notebook                      6.4.12
notebook_shim                 0.2.0
numpy                         1.23.4
packaging                     21.3
pandas                        1.5.1
pandocfilters                 1.5.0
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
Pint                          0.20
pip                           22.3
pkgutil_resolve_name          1.3.10
ply                           3.11
pooch                         1.6.0
prometheus-client             0.15.0
prompt-toolkit                3.0.31
protobuf                      4.21.8
psutil                        5.9.3
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.13.0
pyOpenSSL                     22.1.0
pyparsing                     3.0.9
pyproj                        3.4.0
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
pyrsistent                    0.18.1
pyshp                         2.3.1
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.5
pyvista                       0.36.1
pyvista-xarray                0.1.2
pyzmq                         24.0.1
requests                      2.28.1
scipy                         1.9.3
scooby                        0.7.0
Send2Trash                    1.8.0
setuptools                    65.5.0
Shapely                       1.8.5
sip                           6.7.2
siphon                        0.9
six                           1.16.0
sniffio                       1.3.0
soupsieve                     2.3.2.post1
stack-data                    0.5.1
terminado                     0.17.0
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tornado                       6.2
traitlets                     5.5.0
typing_extensions             4.4.0
unicodedata2                  14.0.0
urllib3                       1.26.11
vtk                           9.2.2
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.4.1
wheel                         0.37.1
wslink                        1.9.0
xarray                        2022.6.0
yarl                          1.8.1
zipp                          3.10.0`

<img width="1206" alt="Screen Shot 2022-11-02 at 9 05 09 AM" src="https://user-images.githubusercontent.com/38228140/199525519-ba814ac1-831e-483a-920e-f1eee32f9258.png">

**Comment by banesullivan** [comment]
@ThomasMGeo, your issue is a bit different and has to do with the installation of VTK. You may need to make sure OpenGL is installed on your machine. This will probably get fixed with just: `apt-get install -y libgl1-mesa-glx`. Otherwise, ping me

**Comment by banesullivan** [comment]
I'm going to close due to inactivity and that I think this issue should be fairly easy to resolve. @almaniac, I am definitely not trying to dismiss your problem, so please follow up if you still need help install pvvista-xarray!
