### ISSUE TITLE
module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by cadasa** [pyvista/pyvista-xarray#47]
I have this error though I use the latest np version 1.24.2:

`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by cadasa** [comment]
I updated vtk and solved the problem

**Comment by banesullivan** [comment]
vtk `9.0.3`  requires numpy<1.24

I recommend keeping VTK and most all packages up to date
