### ISSUE TITLE
Add an Example Working with Weather Radar Data

### ISSUE THREAD

**Issue by mgrover1** [pyvista/pyvista-xarray#51]
We would like to use this to work with weather radar data, which is in polar coordinates (azimuth and range)

Here is an example of plotting the data in 2 dimensions
https://docs.openradarscience.org/projects/xradar/en/stable/notebooks/plot-ppi.html

Here is a sample file
[sample-sweep.nc.zip](https://github.com/pyvista/pyvista-xarray/files/11821532/sample-sweep.nc.zip)

**Comment by banesullivan** [comment]
This was impplemented in #53 and there is a new example notebook uner `examples/radar.ipynb`
