### ISSUE TITLE
Investigate shared coordinates for structured grids 

### ISSUE THREAD

**Issue by johnkit** [pyvista/pyvista-xarray#9]
Seb knows that vtk has some features for interlacing the separate x/y/z arrays without having to copy. He and Bane will discuss offline.

**Comment by banesullivan** [comment]
`vtkSOADataArrayTemplate` is not currently fully implemented in VTK and needs substantial work to leverage. Closing this issue until future consideration. In the meantime, we will continue to memcopy `vtkStructuredGrid` points
